project:
  type: book
  output-dir: ../docs

book:
  title: "Ecological Economics"
  subtitle: "HEKA22 -- VT26"
  author: Jonas Kreutzer
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lecture-1.qmd
    - references.qmd

bibliography: ../references.bib

format:
  pjk_theme-html:
    toc: true
