project:
  type: book
  render:
    - "*.qmd"
    - "lectures/*.qmd"
    - "!slides/"
    - "!lectures/lecture-8.qmd"

book:
  title: "Ecological Economics"
  subtitle: "HEKA22---VT26"
  author: Jonas Kreutzer
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/lecture-1.qmd
        - lectures/lecture-2.qmd
        - lectures/lecture-3.qmd
        - lectures/lecture-4.qmd
        - lectures/lecture-5.qmd
        - lectures/lecture-6.qmd
        - lectures/lecture-7.qmd
        - lectures/lecture-8.qmd
        - lectures/seminar.qmd
    - references.qmd

format:
  pjk_theme-html:
    toc: true
    number-sections: true
    include-in-header:
      - text: |
          <script data-goatcounter="https://pjkreutzer.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>
