project:
  type: book

book:
  title: "Ecological Economics"
  subtitle: "HEKA22---VT26"
  author: Jonas Kreutzer
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/lecture-1.qmd
        - lectures/lecture-2.qmd
        - lectures/lecture-3.qmd
        - lectures/lecture-4.qmd
    - references.qmd

format:
  pjk_theme-html:
    toc: true
