---
subtitle: "HEKA22---VT26, Lund University"
---

# Ecological Economics {.unnumbered}

## Course Overview

This is the companion website for HEKA22 Ecological Economics at Lund University, VT26.

### Learning Objectives


::: {.callout-tip}

## By the end of this course you should:

Demonstrate the ability to independently apply anthropological, historical, sociological, and [economic perspectives]{.text-royal-blue-400} to environmental issues,

- demonstrate the ability to convey in-depth knowledge of human ecology in both spoken and written communication,

- demonstrate the ability to conduct subject-related information searches, evaluate information, and master reference management.

- demonstrate the ability to engage in informed discussion of the relationship between environmental problems and economic growth,

:::

### Schedule

| Date | Lecture | Topic | Slides |
|:-----|-------:|:------------|--------|
| Wed 29 Apr || Course Introduction | [Slides](#slides) |
| Wed 6 May (AM) | 1 | [Introduction to Ecological Economics](lectures/lecture-1.html) | [Slides](lectures/lecture-1.html#slides) |
| Wed 6 May (PM) | 2 | [Principles of Ecological Economics](lectures/lecture-2.html) | [Slides](lectures/lecture-2.html#slides) |
| Fri 8 May | 3 | [History of Economics and Ecology](lectures/lecture-3.html) ||
| Mon 11 May | 4 | [Raw Materials and Metabolism](lectures/lecture-4.html) | Peer Teaching |
| Wed 13 May | 5 | [Doughnut Economics](lectures/lecture-5.html) | Guest Lecture |
| Tue 19 May | 6 | [Markets and Their Invisible Foundations](lectures/lecture-6.html) |[Slides](lectures/lecture-6.html#slides)|
| Thu 21 May | 7 | [Degrowth](lectures/lecture-7.html) ||
| Tue 26 May | 8 | [Bioeconomy](lectures/lecture-8.html) ||
| Thu 28 May || [Seminar: Peer Feedback](lectures/seminar.html) ||

### Assignments

The final assignment for this course is an essay answering **one** of these questions:

1. Formulate a question you found difficult to answer previously, but now have the tools to reason around. Tie your answer to theory, practice, and concrete examples.
2. Choose one economic school of thought to answer the following. Based on the course's material and discussions, argue how your everyday behavior can contribute to "a safe and just place for all within planetary boundaries". How can microeconomics and micropolitics influence larger systems? Use theory, praxis and examples to deepen your analysis.
3. Karl Polanyi's work shows how tightly the economy, culture and society are intertwined. How have your own social and cultural background and experience formed your view on the economy? Point thoroughly to theories from the course to support your reflection.
4. During the course you encountered concepts (for example, "green growth", "Doughnut economics", "Degrowth") that propose different ways for the economy to respond to environmental issues. Chose one of these frames, explain its position and then criticize another frame from it.
5. Propose your own question to me, if it fits the frame of the course and the learning objectives, you may write about something you are passionate about.


**Instructions**: Write a 3000--4000 word essay with a clear structure, consisting of an introduction, a main body with well-developed paragraphs, and a conclusion.
Cite correctly, following the department's citation style. The library offers substantial support (use them!).
Your arguments need to be coupled to the lectures, seminars, and assigned readings for this course.
You are free to use additional material.

You may write this in English, or Swedish.

## Housekeeping {.unnumbered}

The best way to get in touch with me is through mail.
If you have a question that is better discussed in person, please use this link to book a meeting with me [Booking Link](https://outlook.office.com/bookwithme/user/5afbb8ed72e24b0bb02681f0d04cf8cf@lu.se/meetingtype/Yf5IJlNP0kO7Ka1ZVcmfaQ2?anonymous&ep=mlink).

::: {.callout-caution}
This website is a companion website. It is supposed to help you find information regarding the content covered in this module. Canvas is the single source of truth for any administrative questions. If any information here conflicts with Canvas please let me know, but assume that **Canvas is right**.
:::

### Using Computers and AI 

Computers and AI are great tools and for better and worse there is no way around using them anymore.
But you should be mindful about when they add to your learning and when they subtract from it.

I strongly encourage you to leave your computers---anything with a screen really---in your bags during class. Use pen and paper in class, then add a digital summary if you want to.
It will help you stay focused and, more importantly, help others not to get distracted by whatever you would be doing on your screen.
If you must use a screen, please find a seat at the back of the room.

I will not tell you what you should and should not use AI for; as long as it improves your learning outcomes.
However, I think there are some elements you should consider.
Since LLM's entered mainstream use their abilities have grown tremendously.
They can now carry out very complex tasks with high quality results.
Making those decisions is an experience-based skill.
But it still requires human knowledge and intervention to ultimately decide what is true, useful, effective, beautiful.
The bad news: nobody is born with it, it is a skill that needs to be developed.
Developing it requires annoying experimentation, failing and trying again and again, and reflexivity to develop.
The good news: because of that it is something that will make you stand out if you have developed it.

You can use LLM's to develop those skills too.
They can even be extremely helpful for this: you can use them as a tutor testing your knowledge, or as peers to whom you explain concepts you are learning, or as guides helping you understand dense academic text by rephrasing it.
But your learning success will depend on the same factors as with all other learning activities:

1. Make a plan of what you want to understand: what do you think will happen? Did it happen? Why, why not? Applied to AI: before asking the AI think about what *you* believe the answer will be. Was it?

2. Spacing is better than cramming: LLM's generate a lot of text---fast. This can make it tempting to rush from topic to topic, question to question, but your brain needs time to memorize. Active recall---where you try to actively remember information instead of just passively consuming---spaced out over time is the key to remembering things. Applied to AI: take frequent breaks; ask it to quiz you on something you learned yesterday, or last week. Do not just reread old text passively.

3. Actively integrate new knowledge with what you already know. Test yourself to identify gaps in your knowledge. Try to fill them. Then test yourself again.

The central element in all of this is *using your brain actively* not just passively consuming information.

## Slides

{{< slides introduction >}}

